4주차: OAUTH 기능 구현 - 김연수
ssafysandbox-backend/backend pull request #21
Opened 2024-10-31 18:58 UTC by seoburi

### 체크 리스트

- 이전 PR 커밋들이 포함되지 않았는가 확인 (이후에 작성된 커밋만 포함) -> 왜인지 모르겠으나 포함 되어 버림...
- PR 보낸 후 충돌이 나지 않는지 확인 (충돌 해결 필수)

## 📝 작업 내용
- 카카오 인증서버로 authorization code 보내고 accessToken과 refreshToken 받아오는 API 작성
- 카카오 인증서버에서 사용자 정보 받아오는 API 작성
- refreshToken을 사용해 accessToken 재발급 API 작성
- 로그아웃 API 작성

## 보완해야할 내용들
- restApi가 아니라 filter나 interceptor를 사용해 사용자 식별
- 에러코드 담는 DTO 수정 필요
- refreshToken과 accessToken 만료시간 도입
- restTemplate말고 webClient 도입 검토
- HttpEntity를 대체할 Dto 작성

## 💬 리뷰 포인트
1. 쿠키가 어떤 구조인가? -> 쿠키는 스트링 배열의 형태로 저장되는 거 같음 -> 설정 정보도 스트링에 포함
-> 쿠키 설정 시 아래와 같이 그냥 String으로 설정을 넘겨주었음(다만, 재사용성과 가독성이 조금 떨어질 수 있을 거 같음)
```java
ResponseEntity.ok().header("Set-Cookie", "refreshToken=" +refreshToken + "; httponly; sameSite=None; secure"
```
3. 카카오에서 사용자 정보를 어떻게 가져오나? -> 응답 json예시를 보고 그것에 맞춰서 DTO를 설계
4. HttpEntity말고 Dto를 넘겨 주면 어떨까?
HttpEntity의 구조: MultiValueMap을 구현한 HttpHeaders와 T Body.
2개의 필드를 구현한 Dto를 사용하면 좋을 것으로 생각
5. 만료를 어떻게 체크하는 것이 좋을까? -> 카카오에서 받은 토큰 만료기한을 활용할 수 있는지 고민해보겠습니다.

## 🚀 학습에 도움을 줄만한 자료
- 추후 도입할 WebClient 관련 링크:
Spring Reference Doc : https://docs.spring.io/spring-framework/reference/web/webflux-webclient.html
Spring Api Doc : https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.html

2024-11-02 14:35 UTC, aseongjun99 commented on src/main/java/com/ssafy/sandbox/oauth/service/OauthService.java
> +    private final String restApiKey = "0da56a0700a56821782b91c49ce03b42";
따로 숨기는게 좋을 듯 합니다.

2024-11-02 14:35 UTC, aseongjun99 commented on src/main/resources/application.yml
properties 대신 yml로 변경하신 이유가 궁금합니다.

2024-11-04 01:59 UTC, won-joon requested changes

2024-11-04 01:59 UTC, won-joon commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +                .body(null);
이 부분은 어떤 의도인건가요?

2024-11-04 02:39 UTC, won-joon commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +                .body(new ResponseAuthDto(kakaoTokenResponseDto.getAccessToken()));
cookie 설정을 직접 string 으로 작성하는게 아니라 ResponseCookie 를 통해 설정하는 것이 더 좋아보입니다

2024-11-04 02:39 UTC, won-joon commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +        }
`@CookieValue` 를 통해 쿠키를 전달받을 수 있는데 이 부분도 고려해보면 좋을 것 같습니다

2024-11-04 16:22 UTC, famo1245 reviewed
로그인 구현을 위해 쿠키 방식을 사용한 부분이 인상 깊습니다
혹시 별도로 로컬에서 Https 설정을 하여 사용하였는지 궁금하여 물어봅니다!
고생 많으셨습니다!

2024-11-04 16:22 UTC, famo1245 commented on .gitignore
> +build
각각 어떤 디렉토리, 파일인지 여쭤봐도 될까요?

2024-11-04 16:22 UTC, famo1245 commented on build.gradle
> +    // https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
불필요한 주석은 지우면 좋을 것 같습니다!

2024-11-04 16:22 UTC, famo1245 commented on src/main/java/com/ssafy/sandbox/config/RestTempleteConfig.java
> +    }
아무런 설정이 사용되고 있지 않은데 config가 있는 이유를 물어봐도 될까요?

2024-11-04 16:22 UTC, famo1245 commented on src/main/java/com/ssafy/sandbox/email/service/EmailScheduler.java
> +    @Scheduled(fixedRate = 300000)
```suggestion
    @Scheduled(fixedRate = 1000 * 60 * 5)
```
위와 같이 5분이라는 시간이 눈에 잘 들어오도록 명시하는 것도 괜찮을 것 같습니다!
다만 5분마다 해당 트랜잭션이 실행되는 것이 데이터 베이스에 부담이 될 것 같은데 이러한 부분을 고려하셨나요?

2024-11-04 16:22 UTC, famo1245 commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +//        }
해당 부분은 왜 주석 처리가 되었는지 궁금합니다!

2024-11-04 16:22 UTC, famo1245 commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +                .body(null);
아직 토큰 부분이 구현이 안된 것 아닐까요?

2024-11-04 16:22 UTC, famo1245 commented on src/main/java/com/ssafy/sandbox/oauth/dto/KakaoTokenResponseDto.java
> +@Setter
Jackson의 경우 Setter 없이 기본 생성자와 Getter만 있으면 동작하는 것으로 알고있습니다
혹시 별도로 Setter를 사용하는 곳이 있나요?

2024-11-04 16:22 UTC, famo1245 commented on src/main/java/com/ssafy/sandbox/oauth/dto/ErrorResponseDto.java
> +    }
에러 코드 별로 정의한 부분이네요!
조금 더 효율적인 처리를 고민한 것 같아 좋습니다!

2024-11-04 16:22 UTC, famo1245 commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +                .header("Set-Cookie", "refreshToken=" + kakaoTokenResponseDto.getRefreshToken() +"; sameSite=None; httponly; secure")
혹시 kauth 서버에서 넘어온 토큰을 그대로 사용하는 이유가 있을까요?
명세와 맞지 않는 부분이라 여쭤봅니다!

2024-11-05 01:36 UTC, seoburi commented on src/main/java/com/ssafy/sandbox/oauth/service/OauthService.java
> +    private final String restApiKey = "0da56a0700a56821782b91c49ce03b42";
피드백 감사합니다. 숨기겠습니다.

2024-11-05 01:36 UTC, seoburi commented on src/main/resources/application.yml
yml이 가독성이 더 좋아보였습니다.

2024-11-05 01:37 UTC, seoburi commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +                .body(null);
만료기한을 체크해야하는데, 아직 만료기한 체크하는 기능을 구현하지 못했습니다.

2024-11-05 01:38 UTC, seoburi commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +                .body(new ResponseAuthDto(kakaoTokenResponseDto.getAccessToken()));
가독성 때문일까요?

2024-11-05 01:38 UTC, seoburi commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +        }
넵 감사합니다. 그런 어노테이션이 있는 줄 몰랐습니다. 배워갑니다.

2024-11-05 01:41 UTC, seoburi commented on .gitignore
> +build
.run파일은 인텔리제이에서 환경변수를 설정하고 나서 생긴파일입니다. 
Run Configuration에 들어간 후에 Environment Vaiables에 들어가서 환경 변수를 설정하고, 오른쪽 상단에 체크박스를 체크했더니 생겼습니다. 환경변수를 한눈에 확인할 수 있는 파일인 것으로 추측됩니다.

2024-11-05 01:42 UTC, seoburi commented on build.gradle
> +    // https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
피드백 반영하겠습니다!

2024-11-05 01:44 UTC, seoburi commented on src/main/java/com/ssafy/sandbox/config/RestTempleteConfig.java
> +    }
사실 Config가 정확히 어떤 일을 하는 지 이해하지 못합니다. restTemplate 사용 예시를 찾아보다가, config를 사용한 코드가 있어서 참고했습니다. 혹시 알려주실 수 있나요?

2024-11-05 01:49 UTC, seoburi commented on src/main/java/com/ssafy/sandbox/email/service/EmailScheduler.java
> +    @Scheduled(fixedRate = 300000)
그런 식으로 가독성을 개선할 수 있군요. 배워갑니다. 5분마다 삭제해주는 것이 조회 시간을 단축시켜주어 성능에 좋을 것이라고 생각했는데, 오히려 부담이 될까요? 그 점에 대해서 조금 더 고민해보겠습니다.

2024-11-05 01:52 UTC, seoburi commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +//        }
401에러를 리턴했을 때, 프론트와 백사이에서 무한 루프가 발생했습니다. 알고보니 프론트에서 401에러 코드가 아니라 에러메시지를 확인하고 reissue를 보내는 것이었습니다. 그래서 에러를 처리하려고 봤더니 에러메시지를 반환하는 dto 자체를 수정해야해서. 에러를 반환하는 코드를 전부 주석처리해 임시방편으로 해결했습니다. 이와 관련해서는 다음 pr에서 보완하겠습니다.

2024-11-05 02:00 UTC, seoburi commented on src/main/java/com/ssafy/sandbox/oauth/dto/KakaoTokenResponseDto.java
> +@Setter
getter만 있어도 동작한다는 사실을 pr올리고 나서 배웠습니다. 다음 pr에서 setter는 삭제하도록겠습니다.

2024-11-05 02:00 UTC, seoburi commented on src/main/java/com/ssafy/sandbox/oauth/dto/ErrorResponseDto.java
> +    }
감사합니다!

2024-11-05 02:02 UTC, seoburi commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +                .header("Set-Cookie", "refreshToken=" + kakaoTokenResponseDto.getRefreshToken() +"; sameSite=None; httponly; secure")
그대로 사용해도 되는 지 알았습니다. 추후 보완하겠습니다!

2024-11-05 14:08 UTC, famo1245 commented on src/main/java/com/ssafy/sandbox/email/service/EmailScheduler.java
> +    @Scheduled(fixedRate = 300000)
아무래도 5분마다 인증 관련 테이블을 전체 탐색해서 해당 레코드의 expiry_date가 현재 시간보다 이전인지 확인하고 삭제하는 연산하는 전체 과정이다보니 데이터의 수가 늘어날 수록 부담이 증가할 수 있다는 생각이 들었습니다.

2024-11-05 14:10 UTC, famo1245 commented on src/main/java/com/ssafy/sandbox/oauth/controller/OauthController.java
> +//        }
쿠키의 경우 그렇군요, 저는 헤더 방식으로 구현했는데 Http status code만 반환해서 처리가 되어서 궁금증이 들었습니다!

2024-11-05 14:19 UTC, famo1245 commented on src/main/java/com/ssafy/sandbox/config/RestTempleteConfig.java
> +    }
RestTemplate가 여러 군데에서 사용되고 timeout 같은 옵션 등이 동일하게 설정되어 있을 때, 복붙하는 번거로움을 줄이고 가독성을 늘리기 위해서 bean으로 등록하여 DI를 사용하는 방법으로 알고있습니다!
다만 현재에는 사용 빈도도 적고, 별도의 옵션 설정이 없다보니 궁금증이 들었습니다.
하지만 DI를 이용하여 불필요하게 객체를 생성을 막아 메모리를 아끼는 자세는 좋은 것 같습니다

2024-12-25 15:12 UTC, merged